### ISSUE TITLE
api.py : no module named api.util

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#10]
python3 main.py 
Traceback (most recent call last):
  File "/Users/arno/PhpstormProjects/oih-ui/api/api/main.py", line 14, in <module>
    from api.util.solr_query_builder import SolrQueryBuilder
ModuleNotFoundError: No module named 'api.util'

should this be api.api.util???

**Comment by EricSoroos** [comment]
No, It probably should be a relative import -- see the readme in a PR to come in a minute.

**Comment by arnounesco** [comment]
should be ok by now as we could install this
