### ISSUE TITLE
Partner logos on landing page

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/oih-ui#121]
These should be autopopulated through links in the ODISCat entry that drives ODIS registration.

**Comment by jmckenna** [comment]
existing page: https://oceaninfohub.org/partners/

**Comment by pbuttigieg** [comment]
@arnounesco  - is there a field in the ODISCat profile pages where a link to a logo image can be added ? 

If not, can we add it? it will help propagation through the whole system

**Comment by jmckenna** [comment]
Closing this ticket as it is an exact duplicate of https://github.com/iodepo/oih-ui/issues/56

(and existing private ODISCat issue at https://github.com/iodepo/ODISCat/issues/107 )
