### ISSUE TITLE
SOLR should be not be case sensitive in the search

### ISSUE THREAD

**Issue by emarzini** [iodepo/oih-ui#124]
@jmckenna we encountered this problem developing the advanced search.

If the user wants to filter by Provider = AcquaDocs we will have the right results, but it's not so often that the user be careful about the case of a search word. Usually find a set of result using Provider = acquadocs (that doesn't return any results)

Is it a settings on SOLR that you can manage?

**Comment by pbuttigieg** [comment]
![image](https://github.com/user-attachments/assets/2e3852e1-4a4d-4c7e-a4ef-3c8a3cc360bd)
