### ISSUE TITLE
[map-viewer] Provider facet lists url instead of name

### ISSUE THREAD

**Issue by jmckenna** [iodepo/oih-ui#134]
(discovered today by @pbuttigieg )

- problem: in the map-viewer, the `Provider` dropdown lists the urls, but instead should list the provider names (I think in Solr they are stored in the `txt_provider` field)

![provider-new](https://github.com/iodepo/oih-ui/assets/1611709/f98668bd-10aa-49ed-8e37-be516eebbbe9)

cc @dev-marcoC

**Comment by pbuttigieg** [comment]
This seems to be fixed.

**Comment by dev-marcoC** [comment]
Hi @pbuttigieg,

I debugged the case and noticed that now I receive the data differently as you can see, and I am returned id_provider which contains as "name" the urls that are then shown in the filter.

![image](https://github.com/user-attachments/assets/59b67753-1809-4ea9-b5c4-4eb7b21e7bf5)

**Comment by pbuttigieg** [comment]
We tried again, and got the names, so this is oddly inconsistent and I don't know why :)
