### ISSUE TITLE
customization: carousel images

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#139]
following the README, I tried to change the images in the carousel at the bottom of the landing page
```
const PARTNERS = [
  [
    { icon: examplePartner, url: "https://oceanexpert.org/img/logoimageindex.jpg" },
    { icon: examplePartner, url: "https://i0.wp.com/jimfitzpatrick.com/wp-content/uploads/2017/10/Che-Silver-Red.jpg?fit=668%2C1000&ssl=1" },
    { icon: examplePartner, url: "#" },
    { icon: examplePartner, url: "#" },
  ],
```

none of these images are shown

**Comment by dev-marcoC** [comment]
Hi Arno, maybe I explained badly in the readme how this component works.

the url attribute must be populated not with the url of the image to be shown but with the link where the user is redirected when the partner clicks

The icon must be changed in the icon attribute by inserting the image directly into the project and importing it into the configuration file to then use it.

**Comment by it-iode** [comment]
updated the doc and tested
