### ISSUE TITLE
Zoom-out button always performs Zoom-in

### ISSUE THREAD

**Issue by jmckenna** [iodepo/oih-ui#143]
- Zoom-in a few times (click on the "+" icon in lower-right of map)
  - do not use your mouse scroll as that works fine
- now try to Zoom-out (click on the "-" button)
- map actually zooms-in

@pbuttigieg I cannot find another ticket with this issue, as to me this is a total blocker

![Screenshot 2024-09-19 at 1 54 48 PM](https://github.com/user-attachments/assets/ca2c4a0e-2af0-4e67-9883-6203cef4def2)

cc @dev-marcoC

**Comment by pbuttigieg** [comment]
It's a bug, but a very annoying one

**Comment by emarzini** [comment]
Yes we saw it yesterday.

**Comment by dev-marcoC** [comment]
Hi @jmckenna @pbuttigieg ,

I solved this bug in the last commit.

I have updated your dev environment with these latest changes

**Comment by jmckenna** [comment]
thanks @dev-marcoC, fix verified on the dev environment.
