### ISSUE TITLE
remove 'white'space

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#28]
https://github.com/iodepo/oih-ui-docker/issues/13

**Comment by pieterprovoost** [comment]
I don't agree with this, I was about to create an issue for lack of white space when I found this issue. I think the current design looks very compressed and it's hard to see structure in the page. The importance of having sufficient white space is one of the few things I remember from my design classes.

- https://www.everyinteraction.com/articles/give-your-designs-room-to-breathe-with-white-space/
- https://www.code23.com/the-importance-of-white-space-in-web-design/
- https://bootcamp.uxdesign.cc/white-space-in-design-important-guidelines-every-designer-should-know-3efae5594e31

**Comment by pieterprovoost** [comment]
Just a suggestion for the search header (before and after), this makes it less claustrophobic in my opinion. The search results could also be given more structure with a bit of extra white space or by better alignign field names and values. 

<img width="1624" alt="Screenshot 2023-03-17 at 10 56 07" src="https://user-images.githubusercontent.com/490041/225880302-68b98f37-dadd-4dc9-bad3-5b5aaaf1b3a8.png">
<img width="1800" alt="Screenshot 2023-03-17 at 11 29 25" src="https://user-images.githubusercontent.com/490041/225880311-3b6ebb5e-f4f1-429b-94fd-46fd72cb3d93.png">

**Comment by jmckenna** [comment]
I also don't agree with this change.

(to see how it was originally, see staging at https://oih.staging.gatewaygeo.ca/  )

**Comment by pieterprovoost** [comment]
Not an issue if the UI is redone.
