### ISSUE TITLE
background image no longer spans the entire page

### ISSUE THREAD

**Issue by jmckenna** [iodepo/oih-ui#31]
- this causes odd whitepace in header, sidebar, and footer, after performing a search
- see: https://search.oceaninfohub.org/results/?search_text=turtle&page=0

(might be related to recent changes through https://github.com/iodepo/oih-ui/commit/aa6c4bae45de3271573eb9486ac5a48657c9792a ?

**Comment by it-iode** [comment]
this is no longer valid
