### ISSUE TITLE
handle mobile/smart phone displays

### ISSUE THREAD

**Issue by jmckenna** [iodepo/oih-ui#40]
- example screen capture, today, on a Google phone (Android), using its Chrome browser
- the burger-button flashes at top and then disappears on first load (in other words, the page loads without any burger-button menu), and then the facet counts are all mangled together
![mobile](https://user-images.githubusercontent.com/1611709/228028264-f1f66552-382e-4dc0-a34a-85fe9770cfd9.png)

**Comment by it-iode** [comment]
@jmckenna is that still an issue?

**Comment by pieterprovoost** [comment]
Still an issue, this is iPhone and iPad Mini:

![search oceaninfohub org_(iPhone 12 Pro)](https://github.com/iodepo/oih-ui/assets/490041/e67d2134-c791-48a6-b312-3fe80f8fdfe2)

![search oceaninfohub org_(iPad Mini)](https://github.com/iodepo/oih-ui/assets/490041/86dbed81-aa1b-41fd-a806-abc52d0556b5)

**Comment by pieterprovoost** [comment]
Closing this as the UI will be redone.

**Comment by pieterprovoost** [comment]
Happy to reopen, I thought it was appropriate to close this as it was logged as a bug related to the current design, and @arnounesco asked if it was still an issue.

**Comment by arnounesco** [comment]
can be closed, see #62
