### ISSUE TITLE
Fix the URL sharing function

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/oih-ui#64]
Description:

On search.oceaninfohub.org, copy/pasting and sharing a URL to a search result page works. On oceaninfohub.org, it doesn't. 

- [ ] Fix this function

This may be linked to https://github.com/iodepo/oih-ui/issues/49

**Comment by jmckenna** [comment]
- tackled this before on https://oih.staging.gatewaygeo.ca/
- this was difficult to solve, but I managed to do it through `/etc/apache2/sites-enabled/*.conf`
  ```
        <Directory /var/www/oih.staging.gatewaygeo.ca/public_html/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all

                <IfModule mod_rewrite.c>

                    RewriteEngine On
                    # Don't rewrite files or directories
                    RewriteCond %{REQUEST_FILENAME} -f [OR]
                    RewriteCond %{REQUEST_FILENAME} -d
                    RewriteRule ^ - [L]
                    # Rewrite everything else to index.html to allow html5 state links
                    RewriteRule ^ index.html [L]
                       
                </IfModule>

        </Directory>

**Comment by arnounesco** [comment]
This is not a OIH-UI problem but a wordpress problem.
The fix Jeff proposed is the what is already on the Apache server for WP, this does not fix the problem.
see https://github.com/iodepo/OceanInfoHubSite/issues/113

**Comment by arnounesco** [comment]
final solution : https://github.com/iodepo/OIHSiteTheme/issues/3
