### ISSUE TITLE
Front-end portability

### ISSUE THREAD

**Issue by pbuttigieg** [iodepo/oih-ui#92]
The site should be portable - a partner should be able to clone the code and spin up their own front end, just changing some config files for colour themes, links to logos / images / branding, etc. 

New instantiations of the site will have to point (via (a) config file(s)) to their input sources for records and other data. 

Front-end devs should sync carefully with back-end devs to make sure that new instances are stable and can stably connect to their sources within the ODIS Architecture. This issue will be cross-linked to a demonstration case with IOC Africa.

**Comment by it-iode** [comment]
https://github.com/iodepo/oih-ui/blob/feature/restyling/frontend/README.md
